platform :ios, "9.0"
workspace       "LSYNestScrollViewDemo"
project "LSYNestScrollViewDemo.xcodeproj"



target "LSYNestScrollViewDemo" do
project "LSYNestScrollViewDemo.xcodeproj"
use_frameworks!

pod 'Masonry'

end

